# Generated by Django 4.0.3 on 2022-08-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='zip_code',
            field=models.CharField(max_length=150, verbose_name='Zip Code'),
        ),
    ]
