# Generated by Django 4.1.2 on 2022-11-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_venue_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='web',
            field=models.CharField(blank=True, max_length=25, verbose_name='Website Address'),
        ),
    ]
